# Generated by Django 4.0.4 on 2022-09-06 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
