# Generated by Django 4.0.4 on 2022-07-18 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=16)),
                ('price', models.FloatField(max_length=16)),
                ('creation_date', models.DateTimeField()),
                ('category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField()),
                ('listing_name_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positio', to='auctions.listing')),
                ('user_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perso', to='auctions.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(max_length=16)),
                ('listing_name_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='auctions.listing')),
                ('user_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='auctions.listing')),
            ],
        ),
    ]
