# Generated by Django 4.0.4 on 2022-07-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_name_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_name_a', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing_name_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_name_b', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to='auctions.listing'),
        ),
    ]
