# Generated by Django 4.0.4 on 2022-07-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_listing_name_fkey_alter_bid_user_fkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing_name_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_a', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing_name_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_a', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
