# Generated by Django 4.0.4 on 2022-07-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_price_listing_starting_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
    ]
