# Generated by Django 4.0.4 on 2022-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
