# Generated by Django 4.0.4 on 2022-07-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_name_fkey',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_fkey',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing_name_fkey',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_fkey',
            new_name='user',
        ),
    ]
