# Generated by Django 4.0.4 on 2022-08-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
