# Generated by Django 4.0.4 on 2022-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_options_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.FloatField(blank=True, default=-1, max_length=16, null=True),
        ),
    ]
